/*
Kubernetes

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.27.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner{}

// CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner volumeDevice describes a mapping of a raw block device within a container.
type CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner struct {
	// devicePath is the path inside of the container that the device will be mapped to.
	DevicePath string `json:"devicePath"`
	// name must match the name of a persistentVolumeClaim in the pod
	Name string `json:"name"`
}

// NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner instantiates a new CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner(devicePath string, name string) *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner {
	this := CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner{}
	this.DevicePath = devicePath
	this.Name = name
	return &this
}

// NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInnerWithDefaults instantiates a new CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInnerWithDefaults() *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner {
	this := CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner{}
	return &this
}

// GetDevicePath returns the DevicePath field value
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner) GetDevicePath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DevicePath
}

// GetDevicePathOk returns a tuple with the DevicePath field value
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner) GetDevicePathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DevicePath, true
}

// SetDevicePath sets field value
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner) SetDevicePath(v string) {
	o.DevicePath = v
}

// GetName returns the Name field value
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner) SetName(v string) {
	o.Name = v
}

func (o CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["devicePath"] = o.DevicePath
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

type NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner struct {
	value *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner
	isSet bool
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner) Get() *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner {
	return v.value
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner) Set(val *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner(val *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner) *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner {
	return &NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner{value: val, isSet: true}
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


