/*
Kubernetes

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.27.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer{}

// CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer Xline container specification
type CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer struct {
	// Arguments to the entrypoint. The container image's CMD is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container's environment. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. \"$$(VAR_NAME)\" will produce the string literal \"$(VAR_NAME)\". Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell
	Args []string `json:"args,omitempty"`
	// Entrypoint array. Not executed within a shell. The container image's ENTRYPOINT is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container's environment. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. \"$$(VAR_NAME)\" will produce the string literal \"$(VAR_NAME)\". Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell
	Command []string `json:"command,omitempty"`
	// List of environment variables to set in the container. Cannot be updated.
	Env []CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner `json:"env,omitempty"`
	// List of sources to populate environment variables in the container. The keys defined within a source must be a C_IDENTIFIER. All invalid keys will be reported as an event when the container is starting. When a key exists in multiple sources, the value associated with the last source will take precedence. Values defined by an Env with a duplicate key will take precedence. Cannot be updated.
	EnvFrom []CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner `json:"envFrom,omitempty"`
	// Container image name. More info: https://kubernetes.io/docs/concepts/containers/images This field is optional to allow higher level config management to default or override container images in workload controllers like Deployments and StatefulSets.
	Image *string `json:"image,omitempty"`
	// Image pull policy. One of Always, Never, IfNotPresent. Defaults to Always if :latest tag is specified, or IfNotPresent otherwise. Cannot be updated. More info: https://kubernetes.io/docs/concepts/containers/images#updating-images  
	ImagePullPolicy *string `json:"imagePullPolicy,omitempty"`
	Lifecycle *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle `json:"lifecycle,omitempty"`
	LivenessProbe *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe `json:"livenessProbe,omitempty"`
	// Name of the container specified as a DNS_LABEL. Each container in a pod must have a unique name (DNS_LABEL). Cannot be updated.
	Name string `json:"name"`
	// List of ports to expose from the container. Not specifying a port here DOES NOT prevent that port from being exposed. Any port which is listening on the default \"0.0.0.0\" address inside a container will be accessible from the network. Modifying this array with strategic merge patch may corrupt the data. For more information See https://github.com/kubernetes/kubernetes/issues/108255. Cannot be updated.
	Ports []CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerPortsInner `json:"ports,omitempty"`
	ReadinessProbe *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerReadinessProbe `json:"readinessProbe,omitempty"`
	Resources *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResources `json:"resources,omitempty"`
	SecurityContext *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContext `json:"securityContext,omitempty"`
	StartupProbe *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerStartupProbe `json:"startupProbe,omitempty"`
	// Whether this container should allocate a buffer for stdin in the container runtime. If this is not set, reads from stdin in the container will always result in EOF. Default is false.
	Stdin *bool `json:"stdin,omitempty"`
	// Whether the container runtime should close the stdin channel after it has been opened by a single attach. When stdin is true the stdin stream will remain open across multiple attach sessions. If stdinOnce is set to true, stdin is opened on container start, is empty until the first client attaches to stdin, and then remains open and accepts data until the client disconnects, at which time stdin is closed and remains closed until the container is restarted. If this flag is false, a container processes that reads from stdin will never receive an EOF. Default is false
	StdinOnce *bool `json:"stdinOnce,omitempty"`
	// Optional: Path at which the file to which the container's termination message will be written is mounted into the container's filesystem. Message written is intended to be brief final status, such as an assertion failure message. Will be truncated by the node if greater than 4096 bytes. The total message length across all containers will be limited to 12kb. Defaults to /dev/termination-log. Cannot be updated.
	TerminationMessagePath *string `json:"terminationMessagePath,omitempty"`
	// Indicate how the termination message should be populated. File will use the contents of terminationMessagePath to populate the container status message on both success and failure. FallbackToLogsOnError will use the last chunk of container log output if the termination message file is empty and the container exited with an error. The log output is limited to 2048 bytes or 80 lines, whichever is smaller. Defaults to File. Cannot be updated.  
	TerminationMessagePolicy *string `json:"terminationMessagePolicy,omitempty"`
	// Whether this container should allocate a TTY for itself, also requires 'stdin' to be true. Default is false.
	Tty *bool `json:"tty,omitempty"`
	// volumeDevices is the list of block devices to be used by the container.
	VolumeDevices []CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner `json:"volumeDevices,omitempty"`
	// Pod volumes to mount into the container's filesystem. Cannot be updated.
	VolumeMounts []CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeMountsInner `json:"volumeMounts,omitempty"`
	// Container's working directory. If not specified, the container runtime's default will be used, which might be configured in the container image. Cannot be updated.
	WorkingDir *string `json:"workingDir,omitempty"`
}

// NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer instantiates a new CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer(name string) *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer {
	this := CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer{}
	this.Name = name
	return &this
}

// NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerWithDefaults instantiates a new CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerWithDefaults() *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer {
	this := CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer{}
	return &this
}

// GetArgs returns the Args field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetArgs() []string {
	if o == nil || IsNil(o.Args) {
		var ret []string
		return ret
	}
	return o.Args
}

// GetArgsOk returns a tuple with the Args field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetArgsOk() ([]string, bool) {
	if o == nil || IsNil(o.Args) {
		return nil, false
	}
	return o.Args, true
}

// HasArgs returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) HasArgs() bool {
	if o != nil && !IsNil(o.Args) {
		return true
	}

	return false
}

// SetArgs gets a reference to the given []string and assigns it to the Args field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) SetArgs(v []string) {
	o.Args = v
}

// GetCommand returns the Command field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetCommand() []string {
	if o == nil || IsNil(o.Command) {
		var ret []string
		return ret
	}
	return o.Command
}

// GetCommandOk returns a tuple with the Command field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetCommandOk() ([]string, bool) {
	if o == nil || IsNil(o.Command) {
		return nil, false
	}
	return o.Command, true
}

// HasCommand returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) HasCommand() bool {
	if o != nil && !IsNil(o.Command) {
		return true
	}

	return false
}

// SetCommand gets a reference to the given []string and assigns it to the Command field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) SetCommand(v []string) {
	o.Command = v
}

// GetEnv returns the Env field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetEnv() []CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner {
	if o == nil || IsNil(o.Env) {
		var ret []CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner
		return ret
	}
	return o.Env
}

// GetEnvOk returns a tuple with the Env field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetEnvOk() ([]CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner, bool) {
	if o == nil || IsNil(o.Env) {
		return nil, false
	}
	return o.Env, true
}

// HasEnv returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) HasEnv() bool {
	if o != nil && !IsNil(o.Env) {
		return true
	}

	return false
}

// SetEnv gets a reference to the given []CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner and assigns it to the Env field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) SetEnv(v []CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner) {
	o.Env = v
}

// GetEnvFrom returns the EnvFrom field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetEnvFrom() []CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner {
	if o == nil || IsNil(o.EnvFrom) {
		var ret []CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner
		return ret
	}
	return o.EnvFrom
}

// GetEnvFromOk returns a tuple with the EnvFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetEnvFromOk() ([]CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner, bool) {
	if o == nil || IsNil(o.EnvFrom) {
		return nil, false
	}
	return o.EnvFrom, true
}

// HasEnvFrom returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) HasEnvFrom() bool {
	if o != nil && !IsNil(o.EnvFrom) {
		return true
	}

	return false
}

// SetEnvFrom gets a reference to the given []CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner and assigns it to the EnvFrom field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) SetEnvFrom(v []CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner) {
	o.EnvFrom = v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetImage() string {
	if o == nil || IsNil(o.Image) {
		var ret string
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetImageOk() (*string, bool) {
	if o == nil || IsNil(o.Image) {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) HasImage() bool {
	if o != nil && !IsNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given string and assigns it to the Image field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) SetImage(v string) {
	o.Image = &v
}

// GetImagePullPolicy returns the ImagePullPolicy field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetImagePullPolicy() string {
	if o == nil || IsNil(o.ImagePullPolicy) {
		var ret string
		return ret
	}
	return *o.ImagePullPolicy
}

// GetImagePullPolicyOk returns a tuple with the ImagePullPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetImagePullPolicyOk() (*string, bool) {
	if o == nil || IsNil(o.ImagePullPolicy) {
		return nil, false
	}
	return o.ImagePullPolicy, true
}

// HasImagePullPolicy returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) HasImagePullPolicy() bool {
	if o != nil && !IsNil(o.ImagePullPolicy) {
		return true
	}

	return false
}

// SetImagePullPolicy gets a reference to the given string and assigns it to the ImagePullPolicy field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) SetImagePullPolicy(v string) {
	o.ImagePullPolicy = &v
}

// GetLifecycle returns the Lifecycle field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetLifecycle() CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle {
	if o == nil || IsNil(o.Lifecycle) {
		var ret CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle
		return ret
	}
	return *o.Lifecycle
}

// GetLifecycleOk returns a tuple with the Lifecycle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetLifecycleOk() (*CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle, bool) {
	if o == nil || IsNil(o.Lifecycle) {
		return nil, false
	}
	return o.Lifecycle, true
}

// HasLifecycle returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) HasLifecycle() bool {
	if o != nil && !IsNil(o.Lifecycle) {
		return true
	}

	return false
}

// SetLifecycle gets a reference to the given CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle and assigns it to the Lifecycle field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) SetLifecycle(v CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle) {
	o.Lifecycle = &v
}

// GetLivenessProbe returns the LivenessProbe field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetLivenessProbe() CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe {
	if o == nil || IsNil(o.LivenessProbe) {
		var ret CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe
		return ret
	}
	return *o.LivenessProbe
}

// GetLivenessProbeOk returns a tuple with the LivenessProbe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetLivenessProbeOk() (*CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe, bool) {
	if o == nil || IsNil(o.LivenessProbe) {
		return nil, false
	}
	return o.LivenessProbe, true
}

// HasLivenessProbe returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) HasLivenessProbe() bool {
	if o != nil && !IsNil(o.LivenessProbe) {
		return true
	}

	return false
}

// SetLivenessProbe gets a reference to the given CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe and assigns it to the LivenessProbe field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) SetLivenessProbe(v CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) {
	o.LivenessProbe = &v
}

// GetName returns the Name field value
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) SetName(v string) {
	o.Name = v
}

// GetPorts returns the Ports field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetPorts() []CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerPortsInner {
	if o == nil || IsNil(o.Ports) {
		var ret []CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerPortsInner
		return ret
	}
	return o.Ports
}

// GetPortsOk returns a tuple with the Ports field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetPortsOk() ([]CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerPortsInner, bool) {
	if o == nil || IsNil(o.Ports) {
		return nil, false
	}
	return o.Ports, true
}

// HasPorts returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) HasPorts() bool {
	if o != nil && !IsNil(o.Ports) {
		return true
	}

	return false
}

// SetPorts gets a reference to the given []CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerPortsInner and assigns it to the Ports field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) SetPorts(v []CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerPortsInner) {
	o.Ports = v
}

// GetReadinessProbe returns the ReadinessProbe field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetReadinessProbe() CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerReadinessProbe {
	if o == nil || IsNil(o.ReadinessProbe) {
		var ret CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerReadinessProbe
		return ret
	}
	return *o.ReadinessProbe
}

// GetReadinessProbeOk returns a tuple with the ReadinessProbe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetReadinessProbeOk() (*CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerReadinessProbe, bool) {
	if o == nil || IsNil(o.ReadinessProbe) {
		return nil, false
	}
	return o.ReadinessProbe, true
}

// HasReadinessProbe returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) HasReadinessProbe() bool {
	if o != nil && !IsNil(o.ReadinessProbe) {
		return true
	}

	return false
}

// SetReadinessProbe gets a reference to the given CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerReadinessProbe and assigns it to the ReadinessProbe field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) SetReadinessProbe(v CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerReadinessProbe) {
	o.ReadinessProbe = &v
}

// GetResources returns the Resources field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetResources() CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResources {
	if o == nil || IsNil(o.Resources) {
		var ret CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResources
		return ret
	}
	return *o.Resources
}

// GetResourcesOk returns a tuple with the Resources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetResourcesOk() (*CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResources, bool) {
	if o == nil || IsNil(o.Resources) {
		return nil, false
	}
	return o.Resources, true
}

// HasResources returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) HasResources() bool {
	if o != nil && !IsNil(o.Resources) {
		return true
	}

	return false
}

// SetResources gets a reference to the given CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResources and assigns it to the Resources field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) SetResources(v CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResources) {
	o.Resources = &v
}

// GetSecurityContext returns the SecurityContext field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetSecurityContext() CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContext {
	if o == nil || IsNil(o.SecurityContext) {
		var ret CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContext
		return ret
	}
	return *o.SecurityContext
}

// GetSecurityContextOk returns a tuple with the SecurityContext field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetSecurityContextOk() (*CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContext, bool) {
	if o == nil || IsNil(o.SecurityContext) {
		return nil, false
	}
	return o.SecurityContext, true
}

// HasSecurityContext returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) HasSecurityContext() bool {
	if o != nil && !IsNil(o.SecurityContext) {
		return true
	}

	return false
}

// SetSecurityContext gets a reference to the given CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContext and assigns it to the SecurityContext field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) SetSecurityContext(v CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContext) {
	o.SecurityContext = &v
}

// GetStartupProbe returns the StartupProbe field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetStartupProbe() CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerStartupProbe {
	if o == nil || IsNil(o.StartupProbe) {
		var ret CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerStartupProbe
		return ret
	}
	return *o.StartupProbe
}

// GetStartupProbeOk returns a tuple with the StartupProbe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetStartupProbeOk() (*CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerStartupProbe, bool) {
	if o == nil || IsNil(o.StartupProbe) {
		return nil, false
	}
	return o.StartupProbe, true
}

// HasStartupProbe returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) HasStartupProbe() bool {
	if o != nil && !IsNil(o.StartupProbe) {
		return true
	}

	return false
}

// SetStartupProbe gets a reference to the given CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerStartupProbe and assigns it to the StartupProbe field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) SetStartupProbe(v CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerStartupProbe) {
	o.StartupProbe = &v
}

// GetStdin returns the Stdin field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetStdin() bool {
	if o == nil || IsNil(o.Stdin) {
		var ret bool
		return ret
	}
	return *o.Stdin
}

// GetStdinOk returns a tuple with the Stdin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetStdinOk() (*bool, bool) {
	if o == nil || IsNil(o.Stdin) {
		return nil, false
	}
	return o.Stdin, true
}

// HasStdin returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) HasStdin() bool {
	if o != nil && !IsNil(o.Stdin) {
		return true
	}

	return false
}

// SetStdin gets a reference to the given bool and assigns it to the Stdin field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) SetStdin(v bool) {
	o.Stdin = &v
}

// GetStdinOnce returns the StdinOnce field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetStdinOnce() bool {
	if o == nil || IsNil(o.StdinOnce) {
		var ret bool
		return ret
	}
	return *o.StdinOnce
}

// GetStdinOnceOk returns a tuple with the StdinOnce field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetStdinOnceOk() (*bool, bool) {
	if o == nil || IsNil(o.StdinOnce) {
		return nil, false
	}
	return o.StdinOnce, true
}

// HasStdinOnce returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) HasStdinOnce() bool {
	if o != nil && !IsNil(o.StdinOnce) {
		return true
	}

	return false
}

// SetStdinOnce gets a reference to the given bool and assigns it to the StdinOnce field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) SetStdinOnce(v bool) {
	o.StdinOnce = &v
}

// GetTerminationMessagePath returns the TerminationMessagePath field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetTerminationMessagePath() string {
	if o == nil || IsNil(o.TerminationMessagePath) {
		var ret string
		return ret
	}
	return *o.TerminationMessagePath
}

// GetTerminationMessagePathOk returns a tuple with the TerminationMessagePath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetTerminationMessagePathOk() (*string, bool) {
	if o == nil || IsNil(o.TerminationMessagePath) {
		return nil, false
	}
	return o.TerminationMessagePath, true
}

// HasTerminationMessagePath returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) HasTerminationMessagePath() bool {
	if o != nil && !IsNil(o.TerminationMessagePath) {
		return true
	}

	return false
}

// SetTerminationMessagePath gets a reference to the given string and assigns it to the TerminationMessagePath field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) SetTerminationMessagePath(v string) {
	o.TerminationMessagePath = &v
}

// GetTerminationMessagePolicy returns the TerminationMessagePolicy field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetTerminationMessagePolicy() string {
	if o == nil || IsNil(o.TerminationMessagePolicy) {
		var ret string
		return ret
	}
	return *o.TerminationMessagePolicy
}

// GetTerminationMessagePolicyOk returns a tuple with the TerminationMessagePolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetTerminationMessagePolicyOk() (*string, bool) {
	if o == nil || IsNil(o.TerminationMessagePolicy) {
		return nil, false
	}
	return o.TerminationMessagePolicy, true
}

// HasTerminationMessagePolicy returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) HasTerminationMessagePolicy() bool {
	if o != nil && !IsNil(o.TerminationMessagePolicy) {
		return true
	}

	return false
}

// SetTerminationMessagePolicy gets a reference to the given string and assigns it to the TerminationMessagePolicy field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) SetTerminationMessagePolicy(v string) {
	o.TerminationMessagePolicy = &v
}

// GetTty returns the Tty field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetTty() bool {
	if o == nil || IsNil(o.Tty) {
		var ret bool
		return ret
	}
	return *o.Tty
}

// GetTtyOk returns a tuple with the Tty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetTtyOk() (*bool, bool) {
	if o == nil || IsNil(o.Tty) {
		return nil, false
	}
	return o.Tty, true
}

// HasTty returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) HasTty() bool {
	if o != nil && !IsNil(o.Tty) {
		return true
	}

	return false
}

// SetTty gets a reference to the given bool and assigns it to the Tty field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) SetTty(v bool) {
	o.Tty = &v
}

// GetVolumeDevices returns the VolumeDevices field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetVolumeDevices() []CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner {
	if o == nil || IsNil(o.VolumeDevices) {
		var ret []CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner
		return ret
	}
	return o.VolumeDevices
}

// GetVolumeDevicesOk returns a tuple with the VolumeDevices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetVolumeDevicesOk() ([]CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner, bool) {
	if o == nil || IsNil(o.VolumeDevices) {
		return nil, false
	}
	return o.VolumeDevices, true
}

// HasVolumeDevices returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) HasVolumeDevices() bool {
	if o != nil && !IsNil(o.VolumeDevices) {
		return true
	}

	return false
}

// SetVolumeDevices gets a reference to the given []CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner and assigns it to the VolumeDevices field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) SetVolumeDevices(v []CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeDevicesInner) {
	o.VolumeDevices = v
}

// GetVolumeMounts returns the VolumeMounts field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetVolumeMounts() []CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeMountsInner {
	if o == nil || IsNil(o.VolumeMounts) {
		var ret []CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeMountsInner
		return ret
	}
	return o.VolumeMounts
}

// GetVolumeMountsOk returns a tuple with the VolumeMounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetVolumeMountsOk() ([]CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeMountsInner, bool) {
	if o == nil || IsNil(o.VolumeMounts) {
		return nil, false
	}
	return o.VolumeMounts, true
}

// HasVolumeMounts returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) HasVolumeMounts() bool {
	if o != nil && !IsNil(o.VolumeMounts) {
		return true
	}

	return false
}

// SetVolumeMounts gets a reference to the given []CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeMountsInner and assigns it to the VolumeMounts field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) SetVolumeMounts(v []CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerVolumeMountsInner) {
	o.VolumeMounts = v
}

// GetWorkingDir returns the WorkingDir field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetWorkingDir() string {
	if o == nil || IsNil(o.WorkingDir) {
		var ret string
		return ret
	}
	return *o.WorkingDir
}

// GetWorkingDirOk returns a tuple with the WorkingDir field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) GetWorkingDirOk() (*string, bool) {
	if o == nil || IsNil(o.WorkingDir) {
		return nil, false
	}
	return o.WorkingDir, true
}

// HasWorkingDir returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) HasWorkingDir() bool {
	if o != nil && !IsNil(o.WorkingDir) {
		return true
	}

	return false
}

// SetWorkingDir gets a reference to the given string and assigns it to the WorkingDir field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) SetWorkingDir(v string) {
	o.WorkingDir = &v
}

func (o CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Args) {
		toSerialize["args"] = o.Args
	}
	if !IsNil(o.Command) {
		toSerialize["command"] = o.Command
	}
	if !IsNil(o.Env) {
		toSerialize["env"] = o.Env
	}
	if !IsNil(o.EnvFrom) {
		toSerialize["envFrom"] = o.EnvFrom
	}
	if !IsNil(o.Image) {
		toSerialize["image"] = o.Image
	}
	if !IsNil(o.ImagePullPolicy) {
		toSerialize["imagePullPolicy"] = o.ImagePullPolicy
	}
	if !IsNil(o.Lifecycle) {
		toSerialize["lifecycle"] = o.Lifecycle
	}
	if !IsNil(o.LivenessProbe) {
		toSerialize["livenessProbe"] = o.LivenessProbe
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Ports) {
		toSerialize["ports"] = o.Ports
	}
	if !IsNil(o.ReadinessProbe) {
		toSerialize["readinessProbe"] = o.ReadinessProbe
	}
	if !IsNil(o.Resources) {
		toSerialize["resources"] = o.Resources
	}
	if !IsNil(o.SecurityContext) {
		toSerialize["securityContext"] = o.SecurityContext
	}
	if !IsNil(o.StartupProbe) {
		toSerialize["startupProbe"] = o.StartupProbe
	}
	if !IsNil(o.Stdin) {
		toSerialize["stdin"] = o.Stdin
	}
	if !IsNil(o.StdinOnce) {
		toSerialize["stdinOnce"] = o.StdinOnce
	}
	if !IsNil(o.TerminationMessagePath) {
		toSerialize["terminationMessagePath"] = o.TerminationMessagePath
	}
	if !IsNil(o.TerminationMessagePolicy) {
		toSerialize["terminationMessagePolicy"] = o.TerminationMessagePolicy
	}
	if !IsNil(o.Tty) {
		toSerialize["tty"] = o.Tty
	}
	if !IsNil(o.VolumeDevices) {
		toSerialize["volumeDevices"] = o.VolumeDevices
	}
	if !IsNil(o.VolumeMounts) {
		toSerialize["volumeMounts"] = o.VolumeMounts
	}
	if !IsNil(o.WorkingDir) {
		toSerialize["workingDir"] = o.WorkingDir
	}
	return toSerialize, nil
}

type NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer struct {
	value *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer
	isSet bool
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) Get() *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer {
	return v.value
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) Set(val *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer(val *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer {
	return &NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer{value: val, isSet: true}
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


