/*
Kubernetes

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.27.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner{}

// CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner EnvVar represents an environment variable present in a Container.
type CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner struct {
	// Name of the environment variable. Must be a C_IDENTIFIER.
	Name string `json:"name"`
	// Variable references $(VAR_NAME) are expanded using the previously defined environment variables in the container and any service environment variables. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. \"$$(VAR_NAME)\" will produce the string literal \"$(VAR_NAME)\". Escaped references will never be expanded, regardless of whether the variable exists or not. Defaults to \"\".
	Value *string `json:"value,omitempty"`
	ValueFrom *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFrom `json:"valueFrom,omitempty"`
}

// NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner instantiates a new CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner(name string) *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner {
	this := CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner{}
	this.Name = name
	return &this
}

// NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerWithDefaults instantiates a new CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerWithDefaults() *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner {
	this := CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner{}
	return &this
}

// GetName returns the Name field value
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner) SetValue(v string) {
	o.Value = &v
}

// GetValueFrom returns the ValueFrom field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner) GetValueFrom() CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFrom {
	if o == nil || IsNil(o.ValueFrom) {
		var ret CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFrom
		return ret
	}
	return *o.ValueFrom
}

// GetValueFromOk returns a tuple with the ValueFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner) GetValueFromOk() (*CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFrom, bool) {
	if o == nil || IsNil(o.ValueFrom) {
		return nil, false
	}
	return o.ValueFrom, true
}

// HasValueFrom returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner) HasValueFrom() bool {
	if o != nil && !IsNil(o.ValueFrom) {
		return true
	}

	return false
}

// SetValueFrom gets a reference to the given CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFrom and assigns it to the ValueFrom field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner) SetValueFrom(v CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFrom) {
	o.ValueFrom = &v
}

func (o CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.ValueFrom) {
		toSerialize["valueFrom"] = o.ValueFrom
	}
	return toSerialize, nil
}

type NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner struct {
	value *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner
	isSet bool
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner) Get() *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner {
	return v.value
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner) Set(val *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner(val *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner) *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner {
	return &NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner{value: val, isSet: true}
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


