/*
Kubernetes

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.27.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket{}

// CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket TCPSocket specifies an action involving a TCP port.
type CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket struct {
	// Optional: Host name to connect to, defaults to the pod IP.
	Host *string `json:"host,omitempty"`
	// Number or name of the port to access on the container. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME.
	Port string `json:"port"`
}

// NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket instantiates a new CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket(port string) *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket {
	this := CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket{}
	this.Port = port
	return &this
}

// NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocketWithDefaults instantiates a new CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocketWithDefaults() *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket {
	this := CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket{}
	return &this
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket) GetHost() string {
	if o == nil || IsNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket) GetHostOk() (*string, bool) {
	if o == nil || IsNil(o.Host) {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket) HasHost() bool {
	if o != nil && !IsNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket) SetHost(v string) {
	o.Host = &v
}

// GetPort returns the Port field value
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket) GetPort() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Port
}

// GetPortOk returns a tuple with the Port field value
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket) GetPortOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Port, true
}

// SetPort sets field value
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket) SetPort(v string) {
	o.Port = v
}

func (o CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Host) {
		toSerialize["host"] = o.Host
	}
	toSerialize["port"] = o.Port
	return toSerialize, nil
}

type NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket struct {
	value *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket
	isSet bool
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket) Get() *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket {
	return v.value
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket) Set(val *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket(val *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket) *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket {
	return &NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket{value: val, isSet: true}
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


