/*
Kubernetes

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.27.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef{}

// CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef Selects a field of the pod: supports metadata.name, metadata.namespace, `metadata.labels['<KEY>']`, `metadata.annotations['<KEY>']`, spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP, status.podIPs.
type CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef struct {
	// Version of the schema the FieldPath is written in terms of, defaults to \"v1\".
	ApiVersion *string `json:"apiVersion,omitempty"`
	// Path of the field to select in the specified API version.
	FieldPath string `json:"fieldPath"`
}

// NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef instantiates a new CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef(fieldPath string) *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef {
	this := CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef{}
	this.FieldPath = fieldPath
	return &this
}

// NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRefWithDefaults instantiates a new CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRefWithDefaults() *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef {
	this := CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef{}
	return &this
}

// GetApiVersion returns the ApiVersion field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef) GetApiVersion() string {
	if o == nil || IsNil(o.ApiVersion) {
		var ret string
		return ret
	}
	return *o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef) GetApiVersionOk() (*string, bool) {
	if o == nil || IsNil(o.ApiVersion) {
		return nil, false
	}
	return o.ApiVersion, true
}

// HasApiVersion returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef) HasApiVersion() bool {
	if o != nil && !IsNil(o.ApiVersion) {
		return true
	}

	return false
}

// SetApiVersion gets a reference to the given string and assigns it to the ApiVersion field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef) SetApiVersion(v string) {
	o.ApiVersion = &v
}

// GetFieldPath returns the FieldPath field value
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef) GetFieldPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FieldPath
}

// GetFieldPathOk returns a tuple with the FieldPath field value
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef) GetFieldPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FieldPath, true
}

// SetFieldPath sets field value
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef) SetFieldPath(v string) {
	o.FieldPath = v
}

func (o CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApiVersion) {
		toSerialize["apiVersion"] = o.ApiVersion
	}
	toSerialize["fieldPath"] = o.FieldPath
	return toSerialize, nil
}

type NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef struct {
	value *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef
	isSet bool
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef) Get() *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef {
	return v.value
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef) Set(val *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef(val *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef) *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef {
	return &NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef{value: val, isSet: true}
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvInnerValueFromFieldRef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


