/*
Kubernetes

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.27.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner{}

// CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner EnvFromSource represents the source of a set of ConfigMaps
type CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner struct {
	ConfigMapRef *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInnerConfigMapRef `json:"configMapRef,omitempty"`
	// An optional identifier to prepend to each key in the ConfigMap. Must be a C_IDENTIFIER.
	Prefix *string `json:"prefix,omitempty"`
	SecretRef *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInnerSecretRef `json:"secretRef,omitempty"`
}

// NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner instantiates a new CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner() *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner {
	this := CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner{}
	return &this
}

// NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInnerWithDefaults instantiates a new CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInnerWithDefaults() *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner {
	this := CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner{}
	return &this
}

// GetConfigMapRef returns the ConfigMapRef field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner) GetConfigMapRef() CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInnerConfigMapRef {
	if o == nil || IsNil(o.ConfigMapRef) {
		var ret CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInnerConfigMapRef
		return ret
	}
	return *o.ConfigMapRef
}

// GetConfigMapRefOk returns a tuple with the ConfigMapRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner) GetConfigMapRefOk() (*CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInnerConfigMapRef, bool) {
	if o == nil || IsNil(o.ConfigMapRef) {
		return nil, false
	}
	return o.ConfigMapRef, true
}

// HasConfigMapRef returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner) HasConfigMapRef() bool {
	if o != nil && !IsNil(o.ConfigMapRef) {
		return true
	}

	return false
}

// SetConfigMapRef gets a reference to the given CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInnerConfigMapRef and assigns it to the ConfigMapRef field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner) SetConfigMapRef(v CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInnerConfigMapRef) {
	o.ConfigMapRef = &v
}

// GetPrefix returns the Prefix field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner) GetPrefix() string {
	if o == nil || IsNil(o.Prefix) {
		var ret string
		return ret
	}
	return *o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner) GetPrefixOk() (*string, bool) {
	if o == nil || IsNil(o.Prefix) {
		return nil, false
	}
	return o.Prefix, true
}

// HasPrefix returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner) HasPrefix() bool {
	if o != nil && !IsNil(o.Prefix) {
		return true
	}

	return false
}

// SetPrefix gets a reference to the given string and assigns it to the Prefix field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner) SetPrefix(v string) {
	o.Prefix = &v
}

// GetSecretRef returns the SecretRef field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner) GetSecretRef() CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInnerSecretRef {
	if o == nil || IsNil(o.SecretRef) {
		var ret CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInnerSecretRef
		return ret
	}
	return *o.SecretRef
}

// GetSecretRefOk returns a tuple with the SecretRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner) GetSecretRefOk() (*CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInnerSecretRef, bool) {
	if o == nil || IsNil(o.SecretRef) {
		return nil, false
	}
	return o.SecretRef, true
}

// HasSecretRef returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner) HasSecretRef() bool {
	if o != nil && !IsNil(o.SecretRef) {
		return true
	}

	return false
}

// SetSecretRef gets a reference to the given CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInnerSecretRef and assigns it to the SecretRef field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner) SetSecretRef(v CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInnerSecretRef) {
	o.SecretRef = &v
}

func (o CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ConfigMapRef) {
		toSerialize["configMapRef"] = o.ConfigMapRef
	}
	if !IsNil(o.Prefix) {
		toSerialize["prefix"] = o.Prefix
	}
	if !IsNil(o.SecretRef) {
		toSerialize["secretRef"] = o.SecretRef
	}
	return toSerialize, nil
}

type NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner struct {
	value *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner
	isSet bool
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner) Get() *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner {
	return v.value
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner) Set(val *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner(val *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner) *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner {
	return &NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner{value: val, isSet: true}
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerEnvFromInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


