/*
Kubernetes

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.27.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities{}

// CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities The capabilities to add/drop when running containers. Defaults to the default set of capabilities granted by the container runtime. Note that this field cannot be set when spec.os.name is windows.
type CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities struct {
	// Added capabilities
	Add []string `json:"add,omitempty"`
	// Removed capabilities
	Drop []string `json:"drop,omitempty"`
}

// NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities instantiates a new CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities() *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities {
	this := CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities{}
	return &this
}

// NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilitiesWithDefaults instantiates a new CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilitiesWithDefaults() *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities {
	this := CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities{}
	return &this
}

// GetAdd returns the Add field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities) GetAdd() []string {
	if o == nil || IsNil(o.Add) {
		var ret []string
		return ret
	}
	return o.Add
}

// GetAddOk returns a tuple with the Add field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities) GetAddOk() ([]string, bool) {
	if o == nil || IsNil(o.Add) {
		return nil, false
	}
	return o.Add, true
}

// HasAdd returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities) HasAdd() bool {
	if o != nil && !IsNil(o.Add) {
		return true
	}

	return false
}

// SetAdd gets a reference to the given []string and assigns it to the Add field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities) SetAdd(v []string) {
	o.Add = v
}

// GetDrop returns the Drop field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities) GetDrop() []string {
	if o == nil || IsNil(o.Drop) {
		var ret []string
		return ret
	}
	return o.Drop
}

// GetDropOk returns a tuple with the Drop field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities) GetDropOk() ([]string, bool) {
	if o == nil || IsNil(o.Drop) {
		return nil, false
	}
	return o.Drop, true
}

// HasDrop returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities) HasDrop() bool {
	if o != nil && !IsNil(o.Drop) {
		return true
	}

	return false
}

// SetDrop gets a reference to the given []string and assigns it to the Drop field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities) SetDrop(v []string) {
	o.Drop = v
}

func (o CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Add) {
		toSerialize["add"] = o.Add
	}
	if !IsNil(o.Drop) {
		toSerialize["drop"] = o.Drop
	}
	return toSerialize, nil
}

type NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities struct {
	value *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities
	isSet bool
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities) Get() *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities {
	return v.value
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities) Set(val *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities(val *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities) *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities {
	return &NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities{value: val, isSet: true}
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerSecurityContextCapabilities) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


