/*
Kubernetes

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.27.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner{}

// CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner ResourceClaim references one entry in PodSpec.ResourceClaims.
type CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner struct {
	// Name must match the name of one entry in pod.spec.resourceClaims of the Pod where this field is used. It makes that resource available inside a container.
	Name string `json:"name"`
}

// NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner instantiates a new CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner(name string) *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner {
	this := CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner{}
	this.Name = name
	return &this
}

// NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInnerWithDefaults instantiates a new CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInnerWithDefaults() *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner {
	this := CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner{}
	return &this
}

// GetName returns the Name field value
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner) SetName(v string) {
	o.Name = v
}

func (o CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

type NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner struct {
	value *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner
	isSet bool
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner) Get() *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner {
	return v.value
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner) Set(val *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner(val *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner) *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner {
	return &NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner{value: val, isSet: true}
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerResourcesClaimsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


