/*
Kubernetes

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.27.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle{}

// CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle Actions that the management system should take in response to container lifecycle events. Cannot be updated.
type CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle struct {
	PostStart *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecyclePostStart `json:"postStart,omitempty"`
	PreStop *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecyclePreStop `json:"preStop,omitempty"`
}

// NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle instantiates a new CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle() *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle {
	this := CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle{}
	return &this
}

// NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycleWithDefaults instantiates a new CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycleWithDefaults() *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle {
	this := CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle{}
	return &this
}

// GetPostStart returns the PostStart field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle) GetPostStart() CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecyclePostStart {
	if o == nil || IsNil(o.PostStart) {
		var ret CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecyclePostStart
		return ret
	}
	return *o.PostStart
}

// GetPostStartOk returns a tuple with the PostStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle) GetPostStartOk() (*CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecyclePostStart, bool) {
	if o == nil || IsNil(o.PostStart) {
		return nil, false
	}
	return o.PostStart, true
}

// HasPostStart returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle) HasPostStart() bool {
	if o != nil && !IsNil(o.PostStart) {
		return true
	}

	return false
}

// SetPostStart gets a reference to the given CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecyclePostStart and assigns it to the PostStart field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle) SetPostStart(v CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecyclePostStart) {
	o.PostStart = &v
}

// GetPreStop returns the PreStop field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle) GetPreStop() CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecyclePreStop {
	if o == nil || IsNil(o.PreStop) {
		var ret CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecyclePreStop
		return ret
	}
	return *o.PreStop
}

// GetPreStopOk returns a tuple with the PreStop field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle) GetPreStopOk() (*CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecyclePreStop, bool) {
	if o == nil || IsNil(o.PreStop) {
		return nil, false
	}
	return o.PreStop, true
}

// HasPreStop returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle) HasPreStop() bool {
	if o != nil && !IsNil(o.PreStop) {
		return true
	}

	return false
}

// SetPreStop gets a reference to the given CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecyclePreStop and assigns it to the PreStop field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle) SetPreStop(v CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecyclePreStop) {
	o.PreStop = &v
}

func (o CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PostStart) {
		toSerialize["postStart"] = o.PostStart
	}
	if !IsNil(o.PreStop) {
		toSerialize["preStop"] = o.PreStop
	}
	return toSerialize, nil
}

type NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle struct {
	value *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle
	isSet bool
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle) Get() *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle {
	return v.value
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle) Set(val *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle(val *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle) *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle {
	return &NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle{value: val, isSet: true}
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecycle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


