/*
Kubernetes

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.27.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe{}

// CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe Periodic probe of container liveness. Container will be restarted if the probe fails. Cannot be updated. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
type CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe struct {
	Exec *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecyclePostStartExec `json:"exec,omitempty"`
	// Minimum consecutive failures for the probe to be considered failed after having succeeded. Defaults to 3. Minimum value is 1.
	FailureThreshold *int32 `json:"failureThreshold,omitempty"`
	Grpc *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeGrpc `json:"grpc,omitempty"`
	HttpGet *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecyclePostStartHttpGet `json:"httpGet,omitempty"`
	// Number of seconds after the container has started before liveness probes are initiated. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
	InitialDelaySeconds *int32 `json:"initialDelaySeconds,omitempty"`
	// How often (in seconds) to perform the probe. Default to 10 seconds. Minimum value is 1.
	PeriodSeconds *int32 `json:"periodSeconds,omitempty"`
	// Minimum consecutive successes for the probe to be considered successful after having failed. Defaults to 1. Must be 1 for liveness and startup. Minimum value is 1.
	SuccessThreshold *int32 `json:"successThreshold,omitempty"`
	TcpSocket *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket `json:"tcpSocket,omitempty"`
	// Optional duration in seconds the pod needs to terminate gracefully upon probe failure. The grace period is the duration in seconds after the processes running in the pod are sent a termination signal and the time when the processes are forcibly halted with a kill signal. Set this value longer than the expected cleanup time for your process. If this value is nil, the pod's terminationGracePeriodSeconds will be used. Otherwise, this value overrides the value provided by the pod spec. Value must be non-negative integer. The value zero indicates stop immediately via the kill signal (no opportunity to shut down). This is a beta field and requires enabling ProbeTerminationGracePeriod feature gate. Minimum value is 1. spec.terminationGracePeriodSeconds is used if unset.
	TerminationGracePeriodSeconds *int64 `json:"terminationGracePeriodSeconds,omitempty"`
	// Number of seconds after which the probe times out. Defaults to 1 second. Minimum value is 1. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
	TimeoutSeconds *int32 `json:"timeoutSeconds,omitempty"`
}

// NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe instantiates a new CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe() *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe {
	this := CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe{}
	return &this
}

// NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeWithDefaults instantiates a new CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeWithDefaults() *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe {
	this := CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe{}
	return &this
}

// GetExec returns the Exec field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) GetExec() CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecyclePostStartExec {
	if o == nil || IsNil(o.Exec) {
		var ret CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecyclePostStartExec
		return ret
	}
	return *o.Exec
}

// GetExecOk returns a tuple with the Exec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) GetExecOk() (*CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecyclePostStartExec, bool) {
	if o == nil || IsNil(o.Exec) {
		return nil, false
	}
	return o.Exec, true
}

// HasExec returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) HasExec() bool {
	if o != nil && !IsNil(o.Exec) {
		return true
	}

	return false
}

// SetExec gets a reference to the given CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecyclePostStartExec and assigns it to the Exec field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) SetExec(v CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecyclePostStartExec) {
	o.Exec = &v
}

// GetFailureThreshold returns the FailureThreshold field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) GetFailureThreshold() int32 {
	if o == nil || IsNil(o.FailureThreshold) {
		var ret int32
		return ret
	}
	return *o.FailureThreshold
}

// GetFailureThresholdOk returns a tuple with the FailureThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) GetFailureThresholdOk() (*int32, bool) {
	if o == nil || IsNil(o.FailureThreshold) {
		return nil, false
	}
	return o.FailureThreshold, true
}

// HasFailureThreshold returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) HasFailureThreshold() bool {
	if o != nil && !IsNil(o.FailureThreshold) {
		return true
	}

	return false
}

// SetFailureThreshold gets a reference to the given int32 and assigns it to the FailureThreshold field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) SetFailureThreshold(v int32) {
	o.FailureThreshold = &v
}

// GetGrpc returns the Grpc field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) GetGrpc() CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeGrpc {
	if o == nil || IsNil(o.Grpc) {
		var ret CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeGrpc
		return ret
	}
	return *o.Grpc
}

// GetGrpcOk returns a tuple with the Grpc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) GetGrpcOk() (*CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeGrpc, bool) {
	if o == nil || IsNil(o.Grpc) {
		return nil, false
	}
	return o.Grpc, true
}

// HasGrpc returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) HasGrpc() bool {
	if o != nil && !IsNil(o.Grpc) {
		return true
	}

	return false
}

// SetGrpc gets a reference to the given CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeGrpc and assigns it to the Grpc field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) SetGrpc(v CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeGrpc) {
	o.Grpc = &v
}

// GetHttpGet returns the HttpGet field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) GetHttpGet() CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecyclePostStartHttpGet {
	if o == nil || IsNil(o.HttpGet) {
		var ret CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecyclePostStartHttpGet
		return ret
	}
	return *o.HttpGet
}

// GetHttpGetOk returns a tuple with the HttpGet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) GetHttpGetOk() (*CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecyclePostStartHttpGet, bool) {
	if o == nil || IsNil(o.HttpGet) {
		return nil, false
	}
	return o.HttpGet, true
}

// HasHttpGet returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) HasHttpGet() bool {
	if o != nil && !IsNil(o.HttpGet) {
		return true
	}

	return false
}

// SetHttpGet gets a reference to the given CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecyclePostStartHttpGet and assigns it to the HttpGet field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) SetHttpGet(v CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLifecyclePostStartHttpGet) {
	o.HttpGet = &v
}

// GetInitialDelaySeconds returns the InitialDelaySeconds field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) GetInitialDelaySeconds() int32 {
	if o == nil || IsNil(o.InitialDelaySeconds) {
		var ret int32
		return ret
	}
	return *o.InitialDelaySeconds
}

// GetInitialDelaySecondsOk returns a tuple with the InitialDelaySeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) GetInitialDelaySecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.InitialDelaySeconds) {
		return nil, false
	}
	return o.InitialDelaySeconds, true
}

// HasInitialDelaySeconds returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) HasInitialDelaySeconds() bool {
	if o != nil && !IsNil(o.InitialDelaySeconds) {
		return true
	}

	return false
}

// SetInitialDelaySeconds gets a reference to the given int32 and assigns it to the InitialDelaySeconds field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) SetInitialDelaySeconds(v int32) {
	o.InitialDelaySeconds = &v
}

// GetPeriodSeconds returns the PeriodSeconds field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) GetPeriodSeconds() int32 {
	if o == nil || IsNil(o.PeriodSeconds) {
		var ret int32
		return ret
	}
	return *o.PeriodSeconds
}

// GetPeriodSecondsOk returns a tuple with the PeriodSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) GetPeriodSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.PeriodSeconds) {
		return nil, false
	}
	return o.PeriodSeconds, true
}

// HasPeriodSeconds returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) HasPeriodSeconds() bool {
	if o != nil && !IsNil(o.PeriodSeconds) {
		return true
	}

	return false
}

// SetPeriodSeconds gets a reference to the given int32 and assigns it to the PeriodSeconds field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) SetPeriodSeconds(v int32) {
	o.PeriodSeconds = &v
}

// GetSuccessThreshold returns the SuccessThreshold field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) GetSuccessThreshold() int32 {
	if o == nil || IsNil(o.SuccessThreshold) {
		var ret int32
		return ret
	}
	return *o.SuccessThreshold
}

// GetSuccessThresholdOk returns a tuple with the SuccessThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) GetSuccessThresholdOk() (*int32, bool) {
	if o == nil || IsNil(o.SuccessThreshold) {
		return nil, false
	}
	return o.SuccessThreshold, true
}

// HasSuccessThreshold returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) HasSuccessThreshold() bool {
	if o != nil && !IsNil(o.SuccessThreshold) {
		return true
	}

	return false
}

// SetSuccessThreshold gets a reference to the given int32 and assigns it to the SuccessThreshold field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) SetSuccessThreshold(v int32) {
	o.SuccessThreshold = &v
}

// GetTcpSocket returns the TcpSocket field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) GetTcpSocket() CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket {
	if o == nil || IsNil(o.TcpSocket) {
		var ret CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket
		return ret
	}
	return *o.TcpSocket
}

// GetTcpSocketOk returns a tuple with the TcpSocket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) GetTcpSocketOk() (*CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket, bool) {
	if o == nil || IsNil(o.TcpSocket) {
		return nil, false
	}
	return o.TcpSocket, true
}

// HasTcpSocket returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) HasTcpSocket() bool {
	if o != nil && !IsNil(o.TcpSocket) {
		return true
	}

	return false
}

// SetTcpSocket gets a reference to the given CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket and assigns it to the TcpSocket field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) SetTcpSocket(v CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbeTcpSocket) {
	o.TcpSocket = &v
}

// GetTerminationGracePeriodSeconds returns the TerminationGracePeriodSeconds field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) GetTerminationGracePeriodSeconds() int64 {
	if o == nil || IsNil(o.TerminationGracePeriodSeconds) {
		var ret int64
		return ret
	}
	return *o.TerminationGracePeriodSeconds
}

// GetTerminationGracePeriodSecondsOk returns a tuple with the TerminationGracePeriodSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) GetTerminationGracePeriodSecondsOk() (*int64, bool) {
	if o == nil || IsNil(o.TerminationGracePeriodSeconds) {
		return nil, false
	}
	return o.TerminationGracePeriodSeconds, true
}

// HasTerminationGracePeriodSeconds returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) HasTerminationGracePeriodSeconds() bool {
	if o != nil && !IsNil(o.TerminationGracePeriodSeconds) {
		return true
	}

	return false
}

// SetTerminationGracePeriodSeconds gets a reference to the given int64 and assigns it to the TerminationGracePeriodSeconds field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) SetTerminationGracePeriodSeconds(v int64) {
	o.TerminationGracePeriodSeconds = &v
}

// GetTimeoutSeconds returns the TimeoutSeconds field value if set, zero value otherwise.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) GetTimeoutSeconds() int32 {
	if o == nil || IsNil(o.TimeoutSeconds) {
		var ret int32
		return ret
	}
	return *o.TimeoutSeconds
}

// GetTimeoutSecondsOk returns a tuple with the TimeoutSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) GetTimeoutSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.TimeoutSeconds) {
		return nil, false
	}
	return o.TimeoutSeconds, true
}

// HasTimeoutSeconds returns a boolean if a field has been set.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) HasTimeoutSeconds() bool {
	if o != nil && !IsNil(o.TimeoutSeconds) {
		return true
	}

	return false
}

// SetTimeoutSeconds gets a reference to the given int32 and assigns it to the TimeoutSeconds field.
func (o *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) SetTimeoutSeconds(v int32) {
	o.TimeoutSeconds = &v
}

func (o CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Exec) {
		toSerialize["exec"] = o.Exec
	}
	if !IsNil(o.FailureThreshold) {
		toSerialize["failureThreshold"] = o.FailureThreshold
	}
	if !IsNil(o.Grpc) {
		toSerialize["grpc"] = o.Grpc
	}
	if !IsNil(o.HttpGet) {
		toSerialize["httpGet"] = o.HttpGet
	}
	if !IsNil(o.InitialDelaySeconds) {
		toSerialize["initialDelaySeconds"] = o.InitialDelaySeconds
	}
	if !IsNil(o.PeriodSeconds) {
		toSerialize["periodSeconds"] = o.PeriodSeconds
	}
	if !IsNil(o.SuccessThreshold) {
		toSerialize["successThreshold"] = o.SuccessThreshold
	}
	if !IsNil(o.TcpSocket) {
		toSerialize["tcpSocket"] = o.TcpSocket
	}
	if !IsNil(o.TerminationGracePeriodSeconds) {
		toSerialize["terminationGracePeriodSeconds"] = o.TerminationGracePeriodSeconds
	}
	if !IsNil(o.TimeoutSeconds) {
		toSerialize["timeoutSeconds"] = o.TimeoutSeconds
	}
	return toSerialize, nil
}

type NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe struct {
	value *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe
	isSet bool
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) Get() *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe {
	return v.value
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) Set(val *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe(val *CloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe {
	return &NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe{value: val, isSet: true}
}

func (v NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudXlineXlineoperatorV1alpha1XlineClusterSpecContainerLivenessProbe) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


